### ISSUE TITLE
Error in rspec when using 1.2.3

### ISSUE THREAD

**Issue by ChristianEnfield** [dhoer/chef-mozilla_firefox#9]
Unfortunately all of our specs now seem to be failing using version 1.2.3 running chef exec rspec.
Reverted back to 1.1.1. and they run as expected.

Below is the error:
 
```
 7) ois_selenium_node::default windows install sets up selenium node
     Failure/Error:
       ChefSpec::SoloRunner.new(platform: 'windows', version: '2008R2') do
         allow_any_instance_of(Chef::Recipe).to receive(:chrome_version).and_return('48.0.0.0')
       end.converge(described_recipe)

     NoMethodError:
       undefined method `[]' for nil:NilClass
     # C:/Users/CHRIST~1/AppData/Local/Temp/d20160923-9752-1dtq95h/cookbooks/mozilla_firefox/libraries/default.rb:13:in `rescue i                                                               n firefox_version'
     # C:/Users/CHRIST~1/AppData/Local/Temp/d20160923-9752-1dtq95h/cookbooks/mozilla_firefox/libraries/default.rb:8:in `firefox_v                                                               ersion'
     # C:\Users\CHRIST~1\AppData\Local\Temp\d20160923-9752-1dtq95h\cookbooks\selenium_grid\recipes\node.rb:47:in `from_file'
     # C:\Users\CHRIST~1\AppData\Local\Temp\d20160923-9752-1dtq95h\cookbooks\ois_selenium_node\recipes\default.rb:27:in `from_fil                                                               e'
     # ./spec/default_spec.rb:18:in `block (3 levels) in <top (required)>'
     # ./spec/default_spec.rb:46:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # NoMethodError:
     #   undefined method `[]' for nil:NilClass
     #   C:/Users/CHRIST~1/AppData/Local/Temp/d20160923-9752-1dtq95h/cookbooks/mozilla_firefox/libraries/default.rb:10:in `firefo                                                               x_version'
```

**Comment by dhoer** [comment]
I think you will need to mock it just like chrome:
```ruby
allow_any_instance_of(Chef::Recipe).to receive(:firefox_version).and_return('47.0')
```
The code you have shown above is just mocking chrome_version.

**Comment by dhoer** [comment]
Please let me know if mocking fixes the issue.

**Comment by ChristianEnfield** [comment]
Sorry for the delay.
I've mocked this as shown and it is working as expected. 

Thanks for your help with this!
